services:
  db:
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=agens
      - POSTGRES_DB=postgres
    ports:
      - ${LABKIT_PORT_DB:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -q"]
      interval: 2s
      timeout: 3s
      retries: 30
