export { ResearchSession } from "./session";
export type { ResearchSessionOptions } from "./session";
// The two halves, exported so a caller can take one. A read-only adapter that
// never constructs a WriteSurface cannot write -- worth more than a comment
export { ReadSurface, type ResearchReads } from "./read";
export {
  WriteSurface,
  type ResearchWrites,
  type Operation,
  type RetiredOperation,
} from "./write";
export { SessionCore } from "./core";
export { DomainRefusal } from "./refusal";
export {
  READ_GROUPS,
  WRITE_GROUPS,
  OPERATING_GROUPS,
  VERB_GROUPS,
  type ReadGroup,
  type WriteGroup,
  type OperatingGroup,
  type VerbGroup,
} from "./groups";
export {
  systemClock,
  inMemoryEventLog,
  domainEvent,
  createdIn,
  edgesIn,
  UNATTRIBUTED,
} from "./events";
export type {
  Clock,
  AttributionContext,
  AttributionHow,
  CommandContext,
  DomainEvent,
  EventSink,
  // Re-exported from `src/db/domain` through `./events`, so a consumer of the
  // domain barrel can name a change without importing the persistence layer.
  GraphChange,
  NodeCreated,
  EdgeCreated,
  PropsChanged,
} from "./events";
export {
  eventFilter,
  nowQuery,
  notesQuery,
  gateListQuery,
  workListQuery,
  knownAtQuery,
  searchQuery,
  claimsAssertingQuery,
  pursuitsOfQuery,
  originOfQuery,
  gateStatusQuery,
  criteriaGoverningQuery,
  designHistoryQuery,
  contractForQuery,
  stoppedWorkQuery,
  enquiryStatusQuery,
  enquiryInContextQuery,
  whySupportedQuery,
  interpretationHistoryQuery,
  doTheseConflictQuery,
  reproductionOfQuery,
  analysisRevisionQuery,
  reproducibilityOfQuery,
  criterionStandingQuery,
  whyQuery,
  howQuery,
  whatDependsOnQuery,
  neighboursOfQuery,
  proseForQuery,
  reachableQuery,
} from "./queries";
export type {
  EventFilter,
  NowQuery,
  NotesQuery,
  GateListQuery,
  WorkListQuery,
  KnownAtQuery,
  SearchQuery,
  ClaimsAssertingQuery,
  PursuitsOfQuery,
  OriginOfQuery,
  GateStatusQuery,
  CriteriaGoverningQuery,
  DesignHistoryQuery,
  ContractForQuery,
  StoppedWorkQuery,
  EnquiryStatusQuery,
  EnquiryInContextQuery,
  WhySupportedQuery,
  InterpretationHistoryQuery,
  DoTheseConflictQuery,
  ReproductionOfQuery,
  AnalysisRevisionQuery,
  ReproducibilityOfQuery,
  CriterionStandingQuery,
  WhyQuery,
  HowQuery,
  WhatDependsOnQuery,
  NeighboursOfQuery,
  ProseForQuery,
  ReachableQuery,
} from "./queries";
export { GATE_STATES, WORK_STATES } from "./report";
export type {
  Ref,
  ObservationsRef,
  AnalysisRef,
  ReviewRef,
  EnquiryRef,
  NoteRef,
  QuestionRef,
  QuestionStanding,
  AcceptedQuestion,
  AnsweredQuestion,
  KnowledgeSurvey,
  HistoricalSurvey,
  QuestionOrigin,
  EventPage,
  ListedNote,
  AmendmentReport,
  AmendmentRecord,
  ConditionHistory,
  DesignHistory,
  ReinterpretationReport,
  Revision,
  InterpretationHistory,
  ConflictSide,
  ConflictVerdict,
  TaskContract,
  Addressing,
  Conclusion,
  ConcludedClaim,
  SearchGroup,
  SearchMatch,
  RecordedAnalysis,
  ClaimRef,
  EvidenceRef,
  UnitRef,
  EvaluationRef,
  DecisionRef,
  Condition,
  ConclusionRef,
  ChangedConclusion,
  ReplacementReport,
  UnaffectedRecord,
  DependencyReport,
  IdentifiedArtefact,
  ReproductionReport,
  ReproducibilityReport,
  SupportExplanation,
  Verdict,
  GateStatus,
  ListedGate,
  ListedWork,
  WorkState,
  CheckStatus,
  EnquiryStatus,
  EnquiryInContext,
  QuestionBucket,
  EvaluationRecord,
  CriterionRef,
  GateRef,
  WorkRef,
  Kind,
  Cause,
  Explanation,
  ClaimExplanation,
  WorkExplanation,
  EnquiryExplanation,
  GateExplanation,
  Standing,
  How,
  HowStep,
} from "./report";
// Report codecs are the single runtime source for MCP and CLI output.
export {
  claimsAsserting,
  search,
  notes,
  how,
  howStep,
  whatHappened,
  knowledgeSurvey,
  historicalSurvey,
  supportExplanation,
  dependencyReport,
  enquiryQuestion,
  enquiryStatus,
  enquiryInContext,
  designHistory,
  interpretationHistory,
  reproductionReport,
  questionOrigin,
  originOf,
  taskContract,
  criteriaGoverning,
  gateStatus,
  criterionStanding,
  explanation,
  conflictVerdict,
  reproducibilityReport,
  questionRef,
  enquiryRef,
  observationsRef,
  analysisRef,
  recordedAnalysis,
  reviewRef,
  workRef,
  criterionRef,
  gateRef,
  posed,
  noted,
  pursued,
  openedEnquiry,
  recordedObservations,
  sharpenedQuestion,
  synthesised,
  recordedReview,
  closedEnquiry,
  stoppedWork,
  closedGate,
  plannedWork,
  statedCriterion,
  declaredGate,
  evaluatedCriterion,
  acceptedAsUnresolved,
  restated,
  undone,
  verificationReport,
  amendmentReport,
  replacementReport,
  reinterpretationReport,
  pursuits,
  registeredSession,
  gateList,
  workList,
  transcription,
  standing,
} from "./reports";

// The write half's command shapes. `report.ts` above is what a read returns;
// these are what an act takes. Exported so an adapter can hold one -- which is
// what an MCP write tool will need and what inline anonymous shapes prevented.
export { GATE_CLOSURES } from "./commands";
export type {
  Command,
  PursueCommand,
  NoteCommand,
  SharpenCommand,
  RecordObservationsCommand,
  RecordAnalysisCommand,
  ReplacementConclusion,
  RecordReviewCommand,
  CloseEnquiryCommand,
  PlanWorkCommand,
  DeclareGateCommand,
  EvaluateCriterionCommand,
  ReverifyCommand,
  AcceptAsUnresolvedCommand,
  AmendDesignCommand,
  ReplaceAnalysisCommand,
  ReinterpretCommand,
  ClaimIsUndecidedCommand,
  ClaimIsConfirmedCommand,
  PromoteCommand,
} from "./commands";
