export { ResearchSession } from "./session";
export type { ResearchSessionOptions } from "./session";
// The two halves, exported so a caller can take one. A read-only adapter that
// never constructs a WriteSurface cannot write -- worth more than a comment
export { ReadSurface, type ResearchReads } from "./read";
export {
  WriteSurface,
  type ResearchWrites,
  type Operation,
} from "./write";
export { SessionCore } from "./core";
export { openRecord } from "./open";
export type { OpenOptions, OpenRecord } from "./open";
export { DomainRefusal } from "./refusal";
export {
  READ_GROUPS,
  WRITE_GROUPS,
  OPERATING_GROUPS,
  VERB_GROUPS,
  type ReadGroup,
  type WriteGroup,
  type OperatingGroup,
  type VerbGroup,
} from "./groups";
export {
  systemClock,
  inMemoryEventLog,
  domainEvent,
  createdIn,
  edgesIn,
  retractedIn,
  UNATTRIBUTED,
} from "./events";
export type {
  Clock,
  AttributionContext,
  AttributionHow,
  CommandContext,
  DomainEvent,
  RecordedEvent,
  EventSink,
  // Re-exported from `packages/core-db/domain` through `./events`, so a consumer of the
  // domain barrel can name a change without importing the persistence layer.
  GraphChange,
  NodeCreated,
  EdgeCreated,
  NodePropsChanged,
} from "./events";
export {
  eventFilter,
  nowQuery,
  notesQuery,
  gateListQuery,
  workListQuery,
  searchQuery,
  claimsAssertingQuery,
  gateStatusQuery,
  contractForQuery,
  stoppedWorkQuery,
  enquiryStatusQuery,
  enquiryInContextQuery,
  whySupportedQuery,
  analysisRevisionQuery,
  criterionStandingQuery,
  whyQuery,
  neighboursOfQuery,
  proseForQuery,
  reachableQuery,
} from "./queries";
export type {
  EventFilter,
  NowQuery,
  NotesQuery,
  GateListQuery,
  WorkListQuery,
  SearchQuery,
  ClaimsAssertingQuery,
  GateStatusQuery,
  ContractForQuery,
  StoppedWorkQuery,
  EnquiryStatusQuery,
  EnquiryInContextQuery,
  WhySupportedQuery,
  AnalysisRevisionQuery,
  CriterionStandingQuery,
  WhyQuery,
  NeighboursOfQuery,
  ProseForQuery,
  ReachableQuery,
} from "./queries";
export { GATE_STATES, WORK_STATES } from "./report";
export type {
  Ref,
  ObservationsRef,
  AnalysisRef,
  ReviewRef,
  EnquiryRef,
  NoteRef,
  QuestionRef,
  QuestionStanding,
  AcceptedQuestion,
  AnsweredQuestion,
  KnowledgeSurvey,
  EventPage,
  ListedNote,
  AmendmentReport,
  TaskContract,
  Addressing,
  Conclusion,
  ConcludedClaim,
  SearchGroup,
  SearchMatch,
  RecordedAnalysis,
  ClaimRef,
  EvidenceRef,
  UnitRef,
  EvaluationRef,
  DecisionRef,
  Condition,
  ConclusionRef,
  ChangedConclusion,
  UnaffectedRecord,
  IdentifiedArtefact,
  SupportExplanation,
  Verdict,
  GateStatus,
  ListedAnalysis,
  ListedClaim,
  ListedCriterion,
  ListedEnquiry,
  ListedGate,
  ListedWork,
  WorkState,
  CheckStatus,
  EnquiryStatus,
  EnquiryInContext,
  QuestionBucket,
  EvaluationRecord,
  CriterionRef,
  GateRef,
  WorkRef,
  Kind,
  Cause,
  Explanation,
  ClaimExplanation,
  WorkExplanation,
  EnquiryExplanation,
  GateExplanation,
  Standing,
} from "./report";
// Report codecs are the single runtime source for MCP and CLI output.
export {
  claimsAsserting,
  search,
  notes,
  whatHappened,
  knowledgeSurvey,
  supportExplanation,
  enquiryQuestion,
  enquiryStatus,
  enquiryInContext,
  taskContract,
  gateStatus,
  criterionStanding,
  explanation,
  questionRef,
  enquiryRef,
  observationsRef,
  analysisRef,
  recordedAnalysis,
  reviewRef,
  workRef,
  criterionRef,
  gateRef,
  posed,
  noted,
  pursued,
  openedEnquiry,
  recordedObservations,
  synthesised,
  closedEnquiry,
  stoppedWork,
  plannedWork,
  statedCriterion,
  declaredGate,
  evaluatedCriterion,
  acceptedAsUnresolved,
  restated,
  amendmentReport,
  gateList,
  workList,
  transcription,
  standing,
} from "./reports";

// The write half's command shapes. `report.ts` above is what a read returns;
// these are what an act takes. Exported so an adapter can hold one -- which is
// what an MCP write tool will need and what inline anonymous shapes prevented.
export type {
  Command,
  PursueCommand,
  NoteCommand,
  RecordObservationsCommand,
  RecordAnalysisCommand,
  CloseEnquiryCommand,
  PlanWorkCommand,
  DeclareGateCommand,
  EvaluateCriterionCommand,
  AcceptAsUnresolvedCommand,
  AmendDesignCommand,
  ClaimIsConfirmedCommand,
} from "./commands";
