/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugRouteRouteImport } from './routes/workspace.$slug.route'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace.$slug.index'
import { Route as WorkspaceSlugTypeRouteImport } from './routes/workspace.$slug.$type'
import { Route as WorkspaceSlugGraphIdRouteImport } from './routes/workspace.$slug.graph.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRouteRoute = WorkspaceSlugRouteRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)
const WorkspaceSlugTypeRoute = WorkspaceSlugTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)
const WorkspaceSlugGraphIdRoute = WorkspaceSlugGraphIdRouteImport.update({
  id: '/graph/$id',
  path: '/graph/$id',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteRouteWithChildren
  '/workspace/$slug/$type': typeof WorkspaceSlugTypeRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/graph/$id': typeof WorkspaceSlugGraphIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace/$slug/$type': typeof WorkspaceSlugTypeRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/graph/$id': typeof WorkspaceSlugGraphIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteRouteWithChildren
  '/workspace/$slug/$type': typeof WorkspaceSlugTypeRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/graph/$id': typeof WorkspaceSlugGraphIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace/$slug'
    | '/workspace/$slug/$type'
    | '/workspace/$slug/'
    | '/workspace/$slug/graph/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace/$slug/$type'
    | '/workspace/$slug'
    | '/workspace/$slug/graph/$id'
  id:
    | '__root__'
    | '/'
    | '/workspace/$slug'
    | '/workspace/$slug/$type'
    | '/workspace/$slug/'
    | '/workspace/$slug/graph/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSlugRouteRoute: typeof WorkspaceSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/$type': {
      id: '/workspace/$slug/$type'
      path: '/$type'
      fullPath: '/workspace/$slug/$type'
      preLoaderRoute: typeof WorkspaceSlugTypeRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/graph/$id': {
      id: '/workspace/$slug/graph/$id'
      path: '/graph/$id'
      fullPath: '/workspace/$slug/graph/$id'
      preLoaderRoute: typeof WorkspaceSlugGraphIdRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
  }
}

interface WorkspaceSlugRouteRouteChildren {
  WorkspaceSlugTypeRoute: typeof WorkspaceSlugTypeRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugGraphIdRoute: typeof WorkspaceSlugGraphIdRoute
}

const WorkspaceSlugRouteRouteChildren: WorkspaceSlugRouteRouteChildren = {
  WorkspaceSlugTypeRoute: WorkspaceSlugTypeRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugGraphIdRoute: WorkspaceSlugGraphIdRoute,
}

const WorkspaceSlugRouteRouteWithChildren =
  WorkspaceSlugRouteRoute._addFileChildren(WorkspaceSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSlugRouteRoute: WorkspaceSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
