/**
 * Backward-compatible names for report codecs owned by the domain.
 * New MCP tools import codecs directly from ../domain/reports.
 */
export {
  claimsAsserting as claimsAssertingSchema,
  search as searchSchema,
  notes as notesSchema,
  whatHappened as whatHappenedSchema,
  domainEvent as domainEventSchema,
  knowledgeSurvey as knowledgeSurveySchema,
  supportExplanation as supportExplanationSchema,
  enquiryQuestion as enquiryQuestionSchema,
  enquiryStatus as enquiryStatusSchema,
  enquiryInContext as enquiryInContextSchema,
  taskContract as taskContractSchema,
  gateStatus as gateStatusSchema,
  criterionStanding as criterionStandingSchema,
  explanation as explanationSchema,
  questionRef as questionRefSchema,
  enquiryRef as enquiryRefSchema,
  observationsRef as observationsRefSchema,
  analysisRef as analysisRefSchema,
  recordedAnalysis as recordedAnalysisSchema,
  workRef as workRefSchema,
  criterionRef as criterionRefSchema,
  gateRef as gateRefSchema,
  posed as posedSchema,
  noted as notedSchema,
  pursued as pursuedSchema,
  openedEnquiry as openedEnquirySchema,
  recordedObservations as recordedObservationsSchema,
  synthesised as synthesisedSchema,
  closedEnquiry as closedEnquirySchema,
  stoppedWork as stoppedWorkSchema,
  plannedWork as plannedWorkSchema,
  statedCriterion as statedCriterionSchema,
  declaredGate as declaredGateSchema,
  evaluatedCriterion as evaluatedCriterionSchema,
  acceptedAsUnresolved as acceptedAsUnresolvedSchema,
  restated as restatedSchema,
  amendmentReport as amendmentReportSchema,
  gateList as gateListSchema,
  workList as workListSchema,
  transcription as transcriptionSchema,
  standing as standingSchema,
} from "@labkit/core-domain/reports";
